version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "RA/job_455"
